### ISSUE TITLE
Configure download

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#41]
#39 introduced the sentinelsat library to automatically download files directly from the ESA. Right now, the request is hard-coded to a specific time interval and a specific area (Germany). It would be nice to add configuration options for this:

```yaml
download:
  date:
    start: 20190910
    end: 20190911
  country:
    - DE
    - BE
```

This is related to #39 and #1
