### ISSUE TITLE
Limit and offset for web API

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#89]
Requesting all data without limitation right now will likely break things since the result might include billions of points. We should include some kind of pagination, e.g. by supporting a `limit` and `offset` 
 or `page` parameter  

[The GeoJSON specifies pagination](https://jsonapi.org/format/#fetching-pagination)

**Comment by shaardie** [comment]
Seems like it is possible to define the pagination described in [JSON:API](https://jsonapi.org/format/#fetching-pagination) in OpenAPI 3.0 like:

```yaml
components:
  parameters:
    page:
      in: query
      name: page
      style: deepObject
      schema:
        type: object
        properties:
          limit:
            type: integer
            description: Limit number of Items returned.
            minimum: 0
            example: 100
          offset:
            type: integer
            description: Specify the offset of the first hit to return.
            minimum: 0
            example: 100
```

It seems like connexion is not handling deepObject in query parameter very well:

```
2019-11-03 16:10:59,930 - connexion.decorators.validation - INFO - Error while converting value 100 from param <class 'str'> of type real type object to the declared type {'type': 'object', 'properties': {'limit': {'type': 'integer', 'description': 'Limit number of Items returned.', 'minimum': 0, 'example': 100}, 'offset': {'type': 'integer', 'description': 'Specify the offset of the first hit to return.', 'minimum': 0, 'example': 100}}}
2019-11-03 16:10:59,930 - werkzeug - INFO - 127.0.0.1 - - [03/Nov/2019 16:10:59] "GET /api/v1/average/?geoframe=15&geoframe=45&geoframe=20&geoframe=40&country=DE&begin=2019-02-10&end=2019-02-11&page[limit]=100&page[offset]=100 HTTP/1.1" 400 -
```

Also our live documentation does not handle those object well. See
![image](https://user-images.githubusercontent.com/5557272/68087319-fbfed280-fe54-11e9-9b5f-0461d95fb091.png)

I would propose simply using the `limit` and `offset` query parameter like that:

```yaml
components:
  parameters:
    limit:
      in: query
      name: limit
      description: Limit number of Items returned.
      schema:
        type: integer
        minimum: 0
      example: 100
    offset:
      in: query
      name: offset
      description: Specify the offset of the first hit to return.
      schema:
        type: integer
        minimum: 0
      example: 100 
```
